### ISSUE TITLE
How to pick components?

### ISSUE THREAD

**Issue by iwasherefirst2** [Nothing-Works/vuetifyjs-mix-extension#1]
Hey, thank you for this awesome package. I want to use vuetifyjs with its pick-a-la-carte feature in laravel. I found it from your post [here](https://github.com/vuetifyjs/vuetify-loader/issues/49#issuecomment-609514970) (btw, the `laravel-mix.com` link is broken).

I followed your instructions at https://github.com/Nothing-Works/vuetifyjs-mix-extension/blob/master/laravel.md

Calling `npm run dev` (1400kb) and `npm run prod` (52kb) do not throw any errors. However, in the prod version my used components are not included (only in dev, which seems to be the full bundle).

I don't use the vuetify components in a `.vue` file, but I use it in a blade blade file, something like this:

```
@extend('master')

@section('content')
    <div id="app" style="width:500px;margin:auto">
    
      <v-app>
       <v-content>
         <v-container>Hello world</v-container>
  <v-alert type="success">
       I'm a success alert.
     </v-alert>
</v-app>
@endsection
```
 Do you know where I have to specify that?

**Comment by Nothing-Works** [comment]
Hi, thank you for your question and sorry for the delayed response, I have fixed the `laravel-mix.com` website [link](https://laravel-mix.com/extensions/vuetifyjs).

For your question, I think you are using [A-la-carte (tree-shaking)](https://vuetifyjs.com/en/customization/a-la-carte/) feature with `vuetify-loader`, I do not think it's going to work in either `dev` or `prod` if you do not use `.vue` file. (I just tested)

Here, is the reason:

In order to use this feature, you need a way to tell `vuetify-loader` what components you are using which means let the webpack plugin to keep track of all the components you're using. So this happens at the compiling assets time. When you either run `npm run dev` or `npm run prod`.

It's like when you use [CDN](https://vuetifyjs.com/en/getting-started/quick-start/#cdn-usage) and needs tree-shaking I do not think it's possible.

This is my opinion, let me know if I missed something. thanks.

**Comment by iwasherefirst2** [comment]
Thank you for the explanation! I guess your right then. I probably have to choose between the [manual](https://vuetifyjs.com/en/customization/a-la-carte/#manually-importing) way of specifying the components or not using the blade engine. Thank you for your help.
